using FinanceTracker.Infrastructure.Outbox;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace FinanceTracker.Infrastructure.Persistence.Configurations
{
    /// <summary>
    /// Maps OutboxMessage to the "OutboxMessages" table. See
    /// docs/adr/0013-transactional-outbox.md.
    /// </summary>
    public sealed class OutboxMessageConfiguration : IEntityTypeConfiguration<OutboxMessage>
    {
        public void Configure(EntityTypeBuilder<OutboxMessage> builder)
        {
            builder.ToTable("OutboxMessages");

            builder.HasKey(m => m.Id);

            // Generated by EfCoreOutbox before the row is ever saved, never
            // by the database -- the id has to exist first, because it is
            // also the published message's MessageId.
            builder.Property(m => m.Id)
                .ValueGeneratedNever();

            builder.Property(m => m.Type)
                .IsRequired()
                .HasMaxLength(OutboxMessage.MaxTypeLength);

            builder.Property(m => m.EventName)
                .IsRequired()
                .HasMaxLength(OutboxMessage.MaxEventNameLength);

            // jsonb, not text: Postgres rejects a payload that isn't valid
            // JSON at insert time, and the column can be queried with
            // Postgres's JSON operators when inspecting it by hand.
            builder.Property(m => m.Payload)
                .IsRequired()
                .HasColumnType("jsonb");

            builder.Property(m => m.OccurredAt)
                .IsRequired();

            builder.Property(m => m.LastError)
                .HasMaxLength(OutboxMessage.MaxLastErrorLength);

            // The relay's only query is "unprocessed rows, oldest first".
            // A partial index -- covering only rows where ProcessedAt IS
            // NULL -- stays small no matter how many already-processed rows
            // pile up in the table.
            builder.HasIndex(m => m.OccurredAt)
                .HasDatabaseName("IX_OutboxMessages_Unprocessed")
                .HasFilter("\"ProcessedAt\" IS NULL");
        }
    }
}
